version: "3.8"
services:
  reverseproxy:
    build:
      context: udagram-reverseproxy
    image: mohamedamr2001xcc/udagram-reverseproxy:v2
  backend_user:
    build:
      context: udagram-api-user
    image: mohamedamr2001xcc/udagram-api-user:v2
  backend_feed:
    build:
      context: udagram-api-feed
    image: mohamedamr2001xcc/udagram-api-feed:v2
  frontend:
    build:
      context: udagram-frontend
    image: mohamedamr2001xcc/udagram-frontend:v2
