version: "3.8"
services:
  reverseproxy:
    image: mohamedamr2001xcc/udagram-reverseproxy
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend-user
      - backend-feed
  backend-user:
    image: mohamedamr2001xcc/udagram-api-user
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      DB_USERNAME: $POSTGRES_USERNAME
      DB_PASSWORD: $POSTGRES_PASSWORD
      DB_NAME: $POSTGRES_DB
      DB_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_MEDIA_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
  backend-feed:
    image: mohamedamr2001xcc/udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      DB_USERNAME: $POSTGRES_USERNAME
      DB_PASSWORD: $POSTGRES_PASSWORD
      DB_NAME: $POSTGRES_DB
      DB_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_MEDIA_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
  frontend:
    image: mohamedamr2001xcc/udagram-frontend
    ports:
      - "8100:80"
